# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7523a3b92a09addee08857ff2f4e55f7"
name = "Agalaz Virtual Try-On"
application_url = "https://agalaz-virtual-tryon.vercel.app"
embedded = true

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/gdpr"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/api/webhooks/app-uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/update" ]
  uri = "/api/webhooks/app-subscriptions-update"

  [[webhooks.subscriptions]]
  topics = [ "products/create" ]
  uri = "/api/webhooks/products-create"

  [[webhooks.subscriptions]]
  topics = [ "products/update" ]
  uri = "/api/webhooks/products-update"

  [[webhooks.subscriptions]]
  topics = [ "products/delete" ]
  uri = "/api/webhooks/products-delete"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_themes,write_themes"

[auth]
redirect_urls = [ "https://agalaz-virtual-tryon.vercel.app/api/auth/callback" ]

[app_proxy]
url = "https://agalaz-virtual-tryon.vercel.app/api/proxy"
subpath = "tryon"
prefix = "apps"

[pos]
embedded = false

[[extensions]]
type = "theme"
name = "Agalaz Virtual Try-On"
handle = "agalaz-tryon"
