export const metadata = {
  title: 'Terms of Service — Agalaz Virtual Try-On',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white py-16 px-4">
      <div className="max-w-2xl mx-auto prose prose-slate prose-sm">
        <h1 className="text-2xl font-black text-slate-900">Terms of Service</h1>
        <p className="text-slate-400 text-xs">Last updated: March 28, 2026</p>

        <h2>1. Service Description</h2>
        <p>
          Agalaz Virtual Try-On (&quot;the App&quot;) is a Shopify application that provides AI-powered
          virtual clothing try-on functionality for online stores. Merchants install the App to let
          their customers see how garments look on them using uploaded photos.
        </p>

        <h2>2. Account & API Keys</h2>
        <ul>
          <li>Upon installation, merchants receive an API key and free trial credits.</li>
          <li>API keys are confidential. Merchants are responsible for keeping them secure.</li>
          <li>We reserve the right to revoke keys that are misused or shared publicly.</li>
        </ul>

        <h2>3. Plans & Billing</h2>
        <ul>
          <li><strong>Trial</strong>: 5 free renders upon installation.</li>
          <li><strong>Starter</strong>: €150/month — 200 renders/month.</li>
          <li><strong>Growth</strong>: €499/month — 1,000 renders/month.</li>
          <li>Billing is handled via Stripe. Subscriptions renew monthly.</li>
          <li>Unused credits do not roll over to the next month.</li>
          <li>Refunds are handled on a case-by-case basis.</li>
        </ul>

        <h2>4. Acceptable Use</h2>
        <p>Merchants and their customers agree not to:</p>
        <ul>
          <li>Upload illegal, harmful, or explicit content.</li>
          <li>Use the service for any purpose other than virtual clothing try-on.</li>
          <li>Attempt to reverse-engineer, scrape, or abuse the API.</li>
          <li>Exceed rate limits or circumvent credit restrictions.</li>
        </ul>

        <h2>5. AI-Generated Content</h2>
        <p>
          Results are generated by AI and may not perfectly represent actual garment fit.
          The App provides a visual approximation and should not be considered an exact
          representation of size, color, or fit. Merchants should clearly communicate this
          to their customers.
        </p>

        <h2>6. Limitation of Liability</h2>
        <p>
          The App is provided &quot;as is&quot;. We are not liable for any damages arising from
          the use of AI-generated images, including but not limited to inaccurate fit
          representations, lost sales, or customer complaints based on try-on results.
        </p>

        <h2>7. Termination</h2>
        <p>
          Either party may terminate the service at any time. Merchants can uninstall the App
          from their Shopify admin. We may terminate accounts that violate these terms.
          Upon termination, access tokens are revoked and account data is deactivated.
        </p>

        <h2>8. Changes to Terms</h2>
        <p>
          We may update these terms from time to time. Continued use of the App after
          changes constitutes acceptance of the updated terms.
        </p>

        <h2>9. Contact</h2>
        <p>
          For questions about these terms, contact us at:{' '}
          <a href="mailto:support@agalaz.com">support@agalaz.com</a>
        </p>

        <hr />
        <p className="text-slate-400 text-xs">
          Agalaz Virtual Try-On — <a href="https://agalaz.com" className="text-indigo-500">agalaz.com</a>
        </p>
      </div>
    </div>
  );
}
