export const metadata = {
  title: 'Terms of Service — Agalaz Virtual Try-On',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white py-16 px-4">
      <div className="max-w-2xl mx-auto prose prose-slate prose-sm">
        <h1 className="text-2xl font-black text-slate-900">Terms of Service</h1>
        <p className="text-slate-400 text-xs">Last updated: April 17, 2026</p>

        <h2>1. Service Description</h2>
        <p>
          Agalaz Virtual Try-On (&quot;the App&quot;) is a Shopify application that provides AI-powered
          virtual clothing try-on functionality for online stores. Merchants install the App to let
          their customers see how garments look on them using uploaded photos.
        </p>

        <h2>2. Account & API Keys</h2>
        <ul>
          <li>Upon installation, merchants receive an API key and free trial credits.</li>
          <li>API keys are confidential. Merchants are responsible for keeping them secure.</li>
          <li>We reserve the right to revoke keys that are misused or shared publicly.</li>
        </ul>

        <h2>3. Plans & Billing</h2>
        <ul>
          <li><strong>Free trial</strong>: 7 days with 50 renders. Requires a valid payment method.
            Available once per store. If not cancelled before the trial ends, the Starter plan
            activates automatically.</li>
          <li><strong>Starter</strong>: $149/month — 200 renders/month.</li>
          <li><strong>Growth</strong>: $499/month — 1,000 renders/month.</li>
          <li>Billing is handled by Shopify via the Shopify Billing API. Subscriptions renew every 30 days
            on the activation date and appear on your Shopify invoice.</li>
          <li>Unused credits do not roll over to the next month.</li>
          <li>Merchants can cancel at any time from <strong>Settings → Billing → Subscriptions</strong> in
            their Shopify admin, or by uninstalling the app. Cancellation takes effect at the end of the
            current billing period.</li>
          <li>Refunds are handled on a case-by-case basis.</li>
        </ul>

        <h2>4. Acceptable Use</h2>
        <p>Merchants and their customers agree not to:</p>
        <ul>
          <li>Upload illegal, harmful, or explicit content.</li>
          <li>Use the service for any purpose other than virtual clothing try-on.</li>
          <li>Attempt to reverse-engineer, scrape, or abuse the API.</li>
          <li>Exceed rate limits or circumvent credit restrictions.</li>
        </ul>

        <h2>5. AI-Generated Content</h2>
        <p>
          Results are generated by AI and may not perfectly represent actual garment fit.
          The App provides a visual approximation and should not be considered an exact
          representation of size, color, or fit. Merchants should clearly communicate this
          to their customers.
        </p>

        <h2>6. Limitation of Liability</h2>
        <p>
          The App is provided &quot;as is&quot; and &quot;as available&quot;, without warranties of
          any kind, express or implied. To the maximum extent permitted by applicable law:
        </p>
        <ul>
          <li>
            Our total aggregate liability to the merchant arising out of or relating to this
            agreement or the use of the App — whether in contract, tort (including negligence),
            warranty, or otherwise — shall not exceed the total amount paid by the merchant to
            Agalaz in the <strong>three (3) months</strong> preceding the event giving rise to
            the claim.
          </li>
          <li>
            We shall not be liable for any indirect, incidental, special, consequential, or
            punitive damages, including but not limited to loss of profits, revenue, goodwill,
            data, or business opportunities, even if advised of the possibility of such damages.
          </li>
          <li>
            We are not responsible for inaccurate fit or color representations in AI-generated
            images, customer dissatisfaction with try-on results, returns, or third-party service
            outages (Shopify, Google, Supabase, Vercel).
          </li>
          <li>
            Nothing in these terms excludes liability that cannot be excluded under applicable
            mandatory law (e.g., gross negligence, wilful misconduct, death, personal injury, or
            fraud).
          </li>
        </ul>

        <h2>7. Data Processing Agreement (DPA)</h2>
        <p>
          When you install the App, you (as Controller under GDPR) and Agalaz (as Processor)
          automatically enter into our Data Processing Agreement, which forms an integral part of
          these Terms. The DPA governs the processing of personal data (including customer photos
          and merchant data) and lists our sub-processors.
        </p>
        <p>
          You can read and download the DPA at:{' '}
          <a href="/dpa">agalaz-virtual-tryon.vercel.app/dpa</a>. The DPA may be updated from time
          to time; continued use of the App after changes constitutes acceptance of the updated DPA.
        </p>

        <h2>8. Termination</h2>
        <p>
          Either party may terminate the service at any time. Merchants can uninstall the App
          from their Shopify admin. We may terminate accounts that violate these terms.
          Upon termination, access tokens are revoked and account data is deactivated.
        </p>

        <h2>9. Changes to Terms</h2>
        <p>
          We may update these terms from time to time. Continued use of the App after
          changes constitutes acceptance of the updated terms.
        </p>

        <h2>10. Contact</h2>
        <p>
          For questions about these terms, contact us at:{' '}
          <a href="mailto:infoagalaz@gmail.com">infoagalaz@gmail.com</a>
        </p>

        <hr />
        <p className="text-slate-400 text-xs">
          Agalaz Virtual Try-On — <a href="https://agalaz.com" className="text-indigo-500">agalaz.com</a>
        </p>
      </div>
    </div>
  );
}
